# Generated by Django 4.1.7 on 2023-02-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
    ]
