# Generated by Django 4.1.7 on 2023-02-19 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantrating',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantrating',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_ratings', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='restaurant', to='category.category'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantrating',
            unique_together={('owner', 'restaurant')},
        ),
    ]
