# Generated by Django 4.1.7 on 2023-02-19 12:36

import apps.food.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('price', models.IntegerField(default=0)),
                ('delivery_time', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('calorie', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.food.utils.upload_file)),
                ('food_image1', models.ImageField(blank=True, null=True, upload_to=apps.food.utils.upload_file)),
                ('food_image2', models.ImageField(blank=True, null=True, upload_to=apps.food.utils.upload_file)),
                ('food_image3', models.ImageField(blank=True, null=True, upload_to=apps.food.utils.upload_file)),
                ('food_image4', models.ImageField(blank=True, null=True, upload_to=apps.food.utils.upload_file)),
                ('food_image5', models.ImageField(blank=True, null=True, upload_to=apps.food.utils.upload_file)),
            ],
        ),
        migrations.CreateModel(
            name='FoodRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_ratings', to='food.food')),
            ],
        ),
    ]
