# Generated by Django 4.1.7 on 2023-02-19 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrating',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='foods', to='category.category'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='food',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_food', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='foodrating',
            unique_together={('owner', 'food')},
        ),
    ]
