# Generated by Django 4.1.7 on 2023-03-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='instruction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
